/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MacetasRouteImport } from './routes/macetas'
import { Route as PlantasRouteImport } from './routes/plantas'
import { Route as TiendaRouteImport } from './routes/tienda'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MacetasRoute = MacetasRouteImport.update({
  id: '/macetas',
  path: '/macetas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantasRoute = PlantasRouteImport.update({
  id: '/plantas',
  path: '/plantas',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/macetas': typeof MacetasRoute
  '/plantas': typeof PlantasRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/macetas': typeof MacetasRoute
  '/plantas': typeof PlantasRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/macetas': typeof MacetasRoute
  '/plantas': typeof PlantasRoute
  '/tienda': typeof TiendaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/macetas' | '/plantas' | '/tienda'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/macetas' | '/plantas' | '/tienda'
  id: '__root__' | '/' | '/macetas' | '/plantas' | '/tienda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MacetasRoute: typeof MacetasRoute
  PlantasRoute: typeof PlantasRoute
  TiendaRoute: typeof TiendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macetas': {
      id: '/macetas'
      path: '/macetas'
      fullPath: '/macetas'
      preLoaderRoute: typeof MacetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantas': {
      id: '/plantas'
      path: '/plantas'
      fullPath: '/plantas'
      preLoaderRoute: typeof PlantasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MacetasRoute: MacetasRoute,
  PlantasRoute: PlantasRoute,
  TiendaRoute: TiendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
