/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as MacetasRouteImport } from './routes/macetas'
import { Route as PlantasRouteImport } from './routes/plantas'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const MacetasRoute = MacetasRouteImport.update({
  id: '/macetas',
  path: '/macetas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantasRoute = PlantasRouteImport.update({
  id: '/plantas',
  path: '/plantas',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/categorias': typeof CategoriasRoute
  '/macetas': typeof MacetasRoute
  '/plantas': typeof PlantasRoute
  '/tienda': typeof TiendaRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/categorias': typeof CategoriasRoute
  '/macetas': typeof MacetasRoute
  '/plantas': typeof PlantasRoute
  '/tienda': typeof TiendaRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRoute
  '/categorias': typeof CategoriasRoute
  '/macetas': typeof MacetasRoute
  '/plantas': typeof PlantasRoute
  '/tienda': typeof TiendaRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesorios'
    | '/categorias'
    | '/macetas'
    | '/plantas'
    | '/tienda'
    | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesorios'
    | '/categorias'
    | '/macetas'
    | '/plantas'
    | '/tienda'
    | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/accesorios'
    | '/categorias'
    | '/macetas'
    | '/plantas'
    | '/tienda'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesoriosRoute: typeof AccesoriosRoute
  CategoriasRoute: typeof CategoriasRoute
  MacetasRoute: typeof MacetasRoute
  PlantasRoute: typeof PlantasRoute
  TiendaRoute: typeof TiendaRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macetas': {
      id: '/macetas'
      path: '/macetas'
      fullPath: '/macetas'
      preLoaderRoute: typeof MacetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plantas': {
      id: '/plantas'
      path: '/plantas'
      fullPath: '/plantas'
      preLoaderRoute: typeof PlantasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesoriosRoute: AccesoriosRoute,
  CategoriasRoute: CategoriasRoute,
  MacetasRoute: MacetasRoute,
  PlantasRoute: PlantasRoute,
  TiendaRoute: TiendaRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
